language: python
group: travis_latest
dist: xenial
sudo: true

env:
    global:
        - github_master="https://github.com/${TRAVIS_REPO_SLUG}/archive/master.zip"
        - pip_command="pip"
        - python_command="python"
        - WINEDEBUG=fixme-all       # switch off wine fix me messages

addons:
    apt:
        packages:
            - xvfb      # install xvfb virtual framebuffer - this we need for WINE
            - winbind   # needed for WINE

services:   # start services
  - xvfb    # is needed for WINE on headless installation


matrix:
    include:
    - os: windows
      language: sh
      name: "Windows Python 2.7"

      # oddly a secure password under env: global: causes that choco fails
      # so we need to put the option : filter_secrets: false
      # this can be a security issue, check that You dont leak secrets here !
      filter_secrets: false
      before_install:
          - choco install python2
          - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"

    - os: windows
      language: sh
      name: "Windows Python 3.7"

      # oddly a secure password under env: global: causes that choco fails
      # so we need to put the option : filter_secrets: false
      # this can be a security issue, check that You dont leak secrets here !
      filter_secrets: false
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - os: linux
      language: python
      python: '2.7'

    - os: linux
      language: python
      python: '3.4'

    - os: linux
      language: python
      python: '3.5'

    - os: linux
      language: python
      python: '3.6'
      # we can do that also with env - but we dont want to show it on the travis build overview
      before_install:
        - export deploy_on_pypi="True"

    - os: linux
      language: python
      python: '3.7.1'

    - os: linux
      language: python
      python: '3.7-dev'

    - os: linux
      language: python
      python: 'pypy2.7-6.0'

    - os: linux
      language: python
      python: 'pypy3.5-6.0'

    - os: linux
      language: python
      name: "WINE stable 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE stable 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE stable 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE stable 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE stable 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE stable 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE stable 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE stable 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE devel 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE devel 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE devel 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE devel 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE devel 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE devel 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE devel 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE devel 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE staging 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE staging 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE staging 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE staging 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE staging 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE staging 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python2"

    - os: linux
      language: python
      name: "WINE staging 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python3"

    - os: linux
      language: python
      name: "WINE staging 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python3"

    - os: osx
      language: sh
      name: "osX Python 2.7"

    - os: osx
      language: sh
      name: "osX Python 3.7"
      python: "3.7"
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      env:
        # on osx pip and python points to python 2.7 - therefore we have to use pip3 and python3 here
        - pip_command="pip3"
        - python_command="python3"


install:
    - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then service xvfb status ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then chmod 755 ./*.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine_machine.sh ; fi
    - if [[ ${wine_python_version} == "python2" ]]; then ./install_wine_python2_preinstalled.sh ; fi
    - if [[ ${wine_python_version} == "python3" ]]; then ./install_wine_python3_preinstalled.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine_git_portable.sh ; fi

    - ${CMDPREFIX} ${python_command} -m pip install --upgrade pip
    - if [[ $TRAVIS_PYTHON_VERSION == pypy3.5-6.0 ]]; then ${CMDPREFIX} ${pip_command} install "pytest-cov==2.6.0"; fi
    - ${CMDPREFIX} ${pip_command} install codecov pytest pytest-pep8 pytest-cov dill
    - if [[ -f setup.py ]]; then ${CMDPREFIX} ${pip_command} install -e . ; else echo "no setup.py found" ; fi

script:
    - ${CMDPREFIX} ${python_command} -m pytest --pep8 --cov


after_success:
    - ${CMDPREFIX} coverage report
    - ${CMDPREFIX} codecov
